apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-module
  title: Terraform Module
  description: Create a new Terraform module repository.
spec:
  owner: user:default/proffalken
  type: infrastructure

  parameters:
    - title: Module details
      required:
        - name
        - provider
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the Terraform module
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Short description of the module (put full details in the README)
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group
              - kind: User
        provider:
          title: Terraform Provider
          type: string
          enum:
            - aws
            - azure
            - google
            - kubernetes

    - title: Repository location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates/
        values:
          name: ${{ parameters.name }}
          provider: ${{ parameters.provider }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          repo_name: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
          repo_owner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: Terraform module for ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        requireCodeOwnerReviews: true
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
