apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
     backstage.io/techdocs-ref: dir:./docs
     github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
spec:
  type: ${{ values.type }}
  owner: ${{ values.owner }}
  lifecycle: production
